# Generated by Django 3.2.9 on 2022-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220307_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
